# Nombre del microservicio
spring.application.name=autenticacion

# Puerto donde va a correr
server.port=8081

# Conexión a MySQL con XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/autenticaciondb
spring.datasource.username=root
spring.datasource.password=

# Que Spring cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

